### ISSUE TITLE
Type conversions from snowflake to HDFS

### ISSUE THREAD

**Issue by jmccartin** [outrauk/dataiku-plugin-snowflake-hdfs#5]
I have noticed some conversion problems with certain types when doing the bulk unload from snowflake to hdfs. Specifically:
- Columns with type `NUMBER` (such as uprn, with 12 digits) convert to a `DecimalType` in parquet, instead of an `IntegerType` or `LongType`. This can be fixed by a cast to `bigint` in the SQL query:

```
COPY INTO @<managed_stage> FROM (
    SELECT "problematic_column"::bigint AS "problematic_column_fixed"
    FROM <table>)
FILE_FORMAT = (TYPE = PARQUET)
OVERWRITE = TRUE
HEADER = TRUE;
```

**Comment by mklaber** [comment]
@jmccartin can you re-try this on whatever table you saw this?
