### ISSUE TITLE
Timestamp problems

### ISSUE THREAD

**Issue by LeData** [outrauk/dataiku-plugin-snowflake-hdfs#7]
There is an issue with th e plugin when dates are not in NTZ format. Some casting may have to occur.
Message:

`Error in Python process: At line 38: <class 'Exception'>: None: b'During query \'\nCOPY INTO \'@PUBLIC.OUTRA_DATA_DATAIKU_EMR_MANAGED_STAGE/projects/EVENT_DATA/events_hdfs/part\'\nFROM "DSSMANAGED"."EVENT_DATA_events_sf"\nFILE_FORMAT = (TYPE = PARQUET)\nOVERWRITE = TRUE\nHEADER = TRUE;\n \': Error encountered when unloading to PARQUET: TIMESTAMP_TZ and LTZ types are not supported for unloading to Parquet., caused by: SnowflakeSQLException: Error encountered when unloading to PARQUET: TIMESTAMP_TZ and LTZ types are not supported for unloading to Parquet.'`

**Comment by mklaber** [comment]
Solution is to update the `COPY`'s `FROM` to instead of specifying a table, specify a query the casts the `TIMESTAMP_TZ` columns to `TIMESTAMP`. For example:

```sql
COPY INTO '@PUBLIC.OUTRA_DATA_DATAIKU_EMR_MANAGED_STAGE/projects/PPJCUSTOMERLIFETIMEVALUEMODEL/RFM_hdfs_native/part'
FROM (
select "customer_id", "uprn", "total_order_value", "n_purch", "recency", "horizon", "prediction_time"::TIMESTAMP AS "prediction_time", "chunk_nr"
from "DSSMANAGED"."PPJCUSTOMERLIFETIMEVALUEMODEL_rfm"
)
FILE_FORMAT = (TYPE = PARQUET)
OVERWRITE = TRUE
HEADER = TRUE;
```

**Comment by mklaber** [comment]
This is now documented in https://outrauk.atlassian.net/browse/AOBS-491
